project:
  type: website

website:
  description: "Data science portfolio featuring projects in sports analytics, machine learning, and statistical modeling."
  site-url: https://jake-p-bennett.github.io/blog # you must change this appropriately for RSS feeds to work properly
  title: "Jake's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jake-p-bennett

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



