project:
  type: website

website:
  description: "Data science portfolio featuring projects in sports analytics, machine learning, and statistical modeling."
  site-url: https://jake-p-bennett.github.io/blog # you must change this appropriately for RSS feeds to work properly
  title: "Playing with Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jake-p-bennett
      - icon: linkedin
        href: https://www.linkedin.com/in/jacob-peltier-bennett/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



